### ISSUE TITLE
Bug in LArControlFlow/NeutrinoIdTool.cc (or maybe better phrased as sub-optimal way of failing?)

### ISSUE THREAD

**Issue by brucehoward-physics** [PandoraPFA/LArContent#197]
Hi all!

I found a bit of a bug in LArControlFlow/NeutrinoIDTool.cc (or, maybe really this should be described as a sub-optimal way of failing).

When it goes to persist the slice ID features in the metadata, it calls `sliceFeaturesVector.at(sliceIndex).GetFeatureMap(featureMap);`

In the case where the features are not properly filled, then it throws `StatusCodeException(STATUS_CODE_NOT_FOUND)`.

Some of the code has a better handling of this issue, for example the `GetNeutrinoProbability` function has this:
```
if (!this->IsFeatureVectorAvailable())
        return 0.f;
```

When we go to fill the metadata, can we change the if statements to actually check if the feature vector is available, and just not fill the metadata for that if so, rather than throwing an exception? Does this cause any other issues? Something like
```
if (m_persistFeatures)
```
becoming
```
if (m_persistFeatures && sliceFeaturesVector.at(sliceIndex).IsFeatureVectorAvailable())
```

**Comment by brucehoward-physics** [comment]
Just checking in -- any thoughts here?

**Comment by johnmarshall80** [comment]
Hi @brucehoward-physics - Thanks for the reminder about this! I don't think the overall processing should differ whether `m_persistFeatures` is set to `true` or set to `false`, excepting (of course) for the accompanying feature persistency. So, you should then be good to make any associated changes so that the processing/outcome is unchanged by `m_persistFeatures` _and_ so that you're actually happy with what is persisted, in terms of the values provided as a matter of course, vs. some placeholder/default/identifiable value, etc. that you persist if the feature calculation had somehow failed. I hope that makes sense to you. Thanks again.

**Comment by brucehoward-physics** [comment]
Hi @johnmarshall80 - I believe what you say makes sense to me, though I suppose I am also double checking that others agree this can be a problem that we should address and/or if folks had a better solution in mind than what I propose.

I suppose in my potential "solution," there is no alternative default that is saved, but one could pick this up at the analysis level by noting the lack of a saved value. Unless this behavior is not desired broadly? (in which case maybe any solution should save some default values where needed)

**Comment by AndyChappell** [comment]
Resolved in larpandoracontent PR [50](https://github.com/LArSoft/larpandoracontent/pull/50).
